name: 'Code Quality'
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions:
  contents: 'read'
jobs:
  format-goimports-reviser:
    name: 'Format (goimports-reviser)'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: 'Setup (go)'
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: 1.25
      - name: 'Run Go Imports Reviser'
        run: |
          make format-goimports-reviser
      - name: 'Feedback'
        run: |
          git diff HEAD --exit-code --color
  format-prettier:
    name: 'Format (prettier)'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: 'Setup (pnpm)'
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10
      - name: 'Run Prettier'
        run: |
          make format-prettier
      - name: 'Feedback'
        run: |
          git diff HEAD --exit-code --color
  generate:
    name: 'Generate'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: 'Setup (go)'
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: 1.25
      - name: 'Run Generate'
        run: |
          make generate
      - name: 'Feedback'
        run: |
          git diff HEAD --exit-code --color
  test:
    name: 'Unit Tests'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: 'Setup (go)'
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: 1.25
      - name: 'Perform Make'
        run: |
          make test
