name: 'Code Quality'
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions:
  contents: 'read'
jobs:
  format-goimports-reviser:
    name: 'Format (goimports-reviser)'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 'Setup (go)'
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: 1.25
      - name: 'Run Go Imports Reviser'
        run: |
          make format-goimports-reviser
      - name: 'Feedback'
        run: |
          git diff HEAD --exit-code --color
  format-prettier:
    name: 'Format (prettier)'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 'Setup (pnpm)'
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10
      - name: 'Run Prettier'
        run: |
          make format-prettier
      - name: 'Feedback'
        run: |
          git diff HEAD --exit-code --color
  generate:
    name: 'Generate'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 'Setup (go)'
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: 1.25
      - name: 'Run Generate'
        run: |
          make generate
      - name: 'Feedback'
        run: |
          git diff HEAD --exit-code --color
  test:
    name: 'Unit Tests'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 'Setup (go)'
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: 1.25
      - name: 'Perform Make'
        run: |
          make test
